### ISSUE TITLE
isActive support

### ISSUE THREAD

**Issue by deser** [taion/use-named-routes#13]
Does this lib support isActive?

**Comment by taion** [comment]
Yes.

**Comment by chibicode** [comment]
For a beginner like me who's wondering **why** this works with `isActive` - it works b/c `isActive` uses `history.createLocation` under the hood (which is enhanced by `use-named-routes`), like many other methods on React Router.
https://github.com/reactjs/react-router/blob/d782f5cb6e6d7740d36871948293ce10046835df/modules/createTransitionManager.js#L37

And thus you can use `{ name: ..., params: ... }` in addition to `{ pathname: ..., query ... }` for `isActive`:

``` js
// This works
router.isActive({ name: 'widget', params: { widgetId: 'foo' } })
```
