### ISSUE TITLE
createLocation ignores action parameter

### ISSUE THREAD

**Issue by maspwr** [taion/use-named-routes#17]
The [createLocation](https://github.com/taion/use-named-routes/blob/d3348ee761e369263cde6f4c44f7904f47f0d04c/src/index.js#L81) function ignores the action parameter from [createLocationFromRedirectInfo](https://github.com/reactjs/react-router/blob/8707d05b00273590e4d054771b8ae7ae9ad312e3/modules/createTransitionManager.js#L47). Is this intentional? It seems to break the functionality of `IndexRedirect` since the new location is created as a `POP` instead of a `REPLACE`.

**Comment by taion** [comment]
Want to PR a fix? Looks like we just need to pass through the extra arguments to `history.createLocation`.

**Comment by maspwr** [comment]
Yeah, that's what I was thinking. PR incoming...
