### ISSUE TITLE
setRouteLeaveHook returns in callback wrong location object

### ISSUE THREAD

**Issue by deser** [taion/use-named-routes#19]
Consider I do this on`componentDidMount` :  `router.setRouteLeaveHook(this.props.route, nextLocation => { }`

Here `nextLocation` has no `name` (see https://monosnap.com/file/fu4lfRSvY8qytBM6N7138yYbTqaucD)

**Comment by taion** [comment]
That's correct – at that point the route hasn't been matched yet, so no name is applicable.

**Comment by deser** [comment]
I'm not sure that this is right behavior. And actually it might not be a problem to match name for future route.
