### ISSUE TITLE
Getting a path outside of <Link/>

### ISSUE THREAD

**Issue by SachaG** [taion/use-named-routes#20]
Sorry if this is a basic question, but while I understand how to use `<Link to="myRouteName"/>` to get a link to whatever path the `myRouteName` route points too, I'm not sure how to do that outside of `<Link/>`?

For example, [bootstrap-react](http://react-bootstrap.github.io/components.html#navigation) has a `<NavItem/>` component with an `href` attribute:

```
<NavItem eventKey={1} href="/home">NavItem 1 content</NavItem>
```

How would I set the value of that `href` using this package?

**Comment by taion** [comment]
Use LinkContainer in react-router-bootstrap.

**Comment by SachaG** [comment]
Thanks! But what about a more general solution? Is there a generic API to get a path from a route name outside of `<Link/>`?

**Comment by taion** [comment]
`createHref`... but you should be using push/replace on history

**Comment by SachaG** [comment]
Thanks! My idea was that if you have, say, a `Post` object, you might want to create a `Post.getUrl()` method that spits out the path. It could be for something as basic as displaying a post's permalink, for example:

![https://s3.amazonaws.com/f.cl.ly/items/0b17270d0Z0p392n1l0U/Screen%20Shot%202016-06-13%20at%2010.34.50%20AM.png?v=d96bce13](https://s3.amazonaws.com/f.cl.ly/items/0b17270d0Z0p392n1l0U/Screen%20Shot%202016-06-13%20at%2010.34.50%20AM.png?v=d96bce13)

That seems like a fairly common use case? Is there a better way to do it?
