### ISSUE TITLE
getting an empty component when using named-routes

### ISSUE THREAD

**Issue by chrisdrackett** [taion/use-named-routes#21]
I have a very simple project that I got up and running with `react-router` 2.4.0. I then tried to drop in `use-named-routes` based on the example given. When I render my page my container element is empty. I'm not getting any errors, so I'm not sure what the issue is. Here is the code that works:

```
import React from 'react';

import createHistory from 'history/lib/createBrowserHistory';
import { Router, Route, IndexRedirect, browserHistory, useRouterHistory } from 'react-router';
import useNamedRoutes from 'use-named-routes';

// other imports here...

const routes = (
  <Route path="/" component={Index}>
    <Route path="projects/" component={Project}>
      <IndexRedirect to="/project-1" />
      <Route path="project-1" component={Project1}/>
      <Route path="project-2" component={Project2}/>
      <Route path="project-3" component={Project3}/>
    </Route>
  </Route>
);

// The order of history enhancers matters here.
const history = useNamedRoutes(useRouterHistory(createHistory))({ routes });

const router = <Router history={browserHistory} routes={routes} />

export default router;
```

as soon as I swap `browserHistory` in the router to `history` I end up with an empty container.

Thoughts? I'm not sure how to even start troubleshooting.

**Comment by taion** [comment]
You're probably using history v3; the current React Router release is compatible with history v2.

**Comment by chrisdrackett** [comment]
ah, cool, thanks!

**Comment by chrisdrackett** [comment]
might be worth updating the readme, if you install the current install steps history 3.0 will be installed
