### ISSUE TITLE
Please update peer dependencies

### ISSUE THREAD

**Issue by deser** [taion/use-named-routes#22]
npm ERR! peerinvalid Peer use-named-routes@0.3.1 wants history@^2.0.0

Current version of history is 3.0
Thank you!

**Comment by taion** [comment]
That's intentional. Neither this nor React Router currently work with history v3.

**Comment by deser** [comment]
As react-router is going to work with history v3 could you reopen this?

**Comment by taion** [comment]
No, because there's no issue _right now_.
