### ISSUE TITLE
How to use with redux-router

### ISSUE THREAD

**Issue by vadimgoncharov** [taion/use-named-routes#24]
https://github.com/acdlite/redux-router
redux-router init:

```
const store = compose(
  applyMiddleware(m1, m2, m3),
  reduxReactRouter({
    routes,
    createHistory
  }),
  devTools()
)(createStore)(reducer);
```

We can't do like this:

```
reduxReactRouter({
    routes,
    useNamedRoutes(createHistory)
  }),
```

Could you explain, how can we use use-named-routes with redux-router?

**Comment by taion** [comment]
I don't know. You'll have to check the Redux Router docs for how they implement passing additional options to `createHistory`.

**Comment by vadimgoncharov** [comment]
Ok, thanks!

**Comment by vadimgoncharov** [comment]
Just in case someone will face with this problem:

we can use `useNamedRoutes(createHistory)`, but only if we call createHistory function with `({ routes })` argument.

So redux-router doesn't put `routes` argument while executing createHistory:
https://github.com/acdlite/redux-router/blob/master/src/reduxReactRouter.js#L17:L29

```
const history = createAppHistory({
      parseQueryString,
      stringifyQuery,
    });
```

So if we use chaining `useNamedRoutes(useSomeEnhancer(useAnotherEnhancer(createHistory)))` we need to provide options of every enhancer in one object:

```
useNamedRoutes(useSomeEnhancer(useAnotherEnhancer(createHistory)))({
  someOptionForNamedRoutes,
  someOptionForSomeEnhancer,
  someOptionForAnotherEnhancer,
})
```
