### ISSUE TITLE
Invariant Violation: Unknown route: test

### ISSUE THREAD

**Issue by jesusoterogomez** [taion/use-named-routes#25]
Hi, first of all, I wanted to thank for the effort that has been put into this package.

After correctly setting up the named route support, I have been seeing uncaught errors when I have `<Link>` components that point to a route that is not in the routing table yet.

(I'm currently undergoing a major refactoring of my application structure, and I have some broken links that didn't cause any errors unless they were accessed).

Is this by design or is it something that should be fixed?. To reproduce it, it's only needed to create a <Link> element to a path that is not included in the router.

**Comment by taion** [comment]
I wouldn't have added the invariant if it weren't intended. It's exactly to catch this sort of issue, because without the route, there's no way to e.g. generate an `href` for the link.
